/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package edu.hsh.favs.project.escqrs.events.customer;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class CustomerDeletedEvent extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1593246670727499935L;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"CustomerDeletedEvent\",\"namespace\":\"edu.hsh.favs.project.escqrs.events.customer\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerDeletedEvent> ENCODER =
      new BinaryMessageEncoder<CustomerDeletedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerDeletedEvent> DECODER =
      new BinaryMessageDecoder<CustomerDeletedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerDeletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerDeletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerDeletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CustomerDeletedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerDeletedEvent to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerDeletedEvent from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerDeletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
   *     this class
   */
  public static CustomerDeletedEvent fromByteBuffer(java.nio.ByteBuffer b)
      throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.CharSequence username;
  private int age;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the
   * schema. If that is desired then one should use <code>newBuilder()</code>.
   */
  public CustomerDeletedEvent() {}

  /**
   * All-args constructor.
   *
   * @param id The new value for id
   * @param username The new value for username
   * @param age The new value for age
   */
  public CustomerDeletedEvent(
      java.lang.Long id, java.lang.CharSequence username, java.lang.Integer age) {
    this.id = id;
    this.username = username;
    this.age = age;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return id;
      case 1:
        return username;
      case 2:
        return age;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        id = (java.lang.Long) value$;
        break;
      case 1:
        username = (java.lang.CharSequence) value$;
        break;
      case 2:
        age = (java.lang.Integer) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   *
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   *
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'username' field.
   *
   * @return The value of the 'username' field.
   */
  public java.lang.CharSequence getUsername() {
    return username;
  }

  /**
   * Sets the value of the 'username' field.
   *
   * @param value the value to set.
   */
  public void setUsername(java.lang.CharSequence value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'age' field.
   *
   * @return The value of the 'age' field.
   */
  public int getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   *
   * @param value the value to set.
   */
  public void setAge(int value) {
    this.age = value;
  }

  /**
   * Creates a new CustomerDeletedEvent RecordBuilder.
   *
   * @return A new CustomerDeletedEvent RecordBuilder
   */
  public static edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder
      newBuilder() {
    return new edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder();
  }

  /**
   * Creates a new CustomerDeletedEvent RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new CustomerDeletedEvent RecordBuilder
   */
  public static edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder newBuilder(
      edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder other) {
    if (other == null) {
      return new edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder();
    } else {
      return new edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new CustomerDeletedEvent RecordBuilder by copying an existing CustomerDeletedEvent
   * instance.
   *
   * @param other The existing instance to copy.
   * @return A new CustomerDeletedEvent RecordBuilder
   */
  public static edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder newBuilder(
      edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent other) {
    if (other == null) {
      return new edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder();
    } else {
      return new edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder(other);
    }
  }

  /** RecordBuilder for CustomerDeletedEvent instances. */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder
      extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerDeletedEvent>
      implements org.apache.avro.data.RecordBuilder<CustomerDeletedEvent> {

    private long id;
    private java.lang.CharSequence username;
    private int age;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(
        edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerDeletedEvent instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Gets the value of the 'id' field.
     *
     * @return The value.
     */
    public long getId() {
      return id;
    }

    /**
     * Sets the value of the 'id' field.
     *
     * @param value The value of 'id'.
     * @return This builder.
     */
    public edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder setId(
        long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'id' field has been set.
     *
     * @return True if the 'id' field has been set, false otherwise.
     */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'id' field.
     *
     * @return This builder.
     */
    public edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'username' field.
     *
     * @return The value.
     */
    public java.lang.CharSequence getUsername() {
      return username;
    }

    /**
     * Sets the value of the 'username' field.
     *
     * @param value The value of 'username'.
     * @return This builder.
     */
    public edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder setUsername(
        java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.username = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'username' field has been set.
     *
     * @return True if the 'username' field has been set, false otherwise.
     */
    public boolean hasUsername() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'username' field.
     *
     * @return This builder.
     */
    public edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder
        clearUsername() {
      username = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'age' field.
     *
     * @return The value.
     */
    public int getAge() {
      return age;
    }

    /**
     * Sets the value of the 'age' field.
     *
     * @param value The value of 'age'.
     * @return This builder.
     */
    public edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder setAge(
        int value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'age' field has been set.
     *
     * @return True if the 'age' field has been set, false otherwise.
     */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }

    /**
     * Clears the value of the 'age' field.
     *
     * @return This builder.
     */
    public edu.hsh.favs.project.escqrs.events.customer.CustomerDeletedEvent.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerDeletedEvent build() {
      try {
        CustomerDeletedEvent record = new CustomerDeletedEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.username =
            fieldSetFlags()[1] ? this.username : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerDeletedEvent> WRITER$ =
      (org.apache.avro.io.DatumWriter<CustomerDeletedEvent>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerDeletedEvent> READER$ =
      (org.apache.avro.io.DatumReader<CustomerDeletedEvent>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
    out.writeLong(this.id);

    out.writeString(this.username);

    out.writeInt(this.age);
  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.username = in.readString(this.username instanceof Utf8 ? (Utf8) this.username : null);

      this.age = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            this.id = in.readLong();
            break;

          case 1:
            this.username =
                in.readString(this.username instanceof Utf8 ? (Utf8) this.username : null);
            break;

          case 2:
            this.age = in.readInt();
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
