spring:
  profiles:
    active: docker
  application:
    name: discovery-service
server:
  port: 8761
logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    com.memorynotfound: DEBUG
    org.apache.kafka.*: ERROR
---
spring:
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
  config:
    activate:
      on-profile: development
eureka:
  instance:
    preferIpAddress: true
---
spring:
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
  config:
    activate:
      on-profile: docker
eureka:
  instance:
    preferIpAddress: true
